apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: redirector
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      run: redirector
    name: redirector
  spec:
    replicas: 1
    selector:
      run: redirector
    strategy:
      resources:
        requests:
          cpu: 20m
          memory: 20Mi
        limits:
          cpu: 200m
          memory: 200Mi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: redirector
      spec:
        containers:
        - env:
          - name: REDIRECTOR_DESTINATION
            valueFrom:
                configMapKeyRef:
                  name: redirector
                  key: redirector.destination
          - name: REDIRECTOR_TYPE
            valueFrom:
                configMapKeyRef:
                  name: redirector
                  key: redirector.type
          image: registry.centos.org/mattermost/nginx-redirector:latest
          imagePullPolicy: Always
          name: redirector
          ports:
          - containerPort: 8080
            protocol: TCP
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: redirector
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: redirector
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
